# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('ingredientes', models.TextField()),
                ('imagen', models.TextField()),
                ('descripcion', models.TextField()),
                ('tipo', models.TextField(choices=[('Aperitivo', 'Aperitivo'), ('Plato Fuerte', 'Plato Fuerte'), ('Postre', 'Postre')])),
                ('temperatura', models.TextField(choices=[('Frio', 'Frio'), ('Caliente', 'Caliente')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('direccion', models.TextField()),
                ('duenio', models.TextField(max_length=50)),
                ('telefono', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('rol', models.TextField(choices=[('Cliente', 'Cliente'), ('Ayudante', 'Ayudante'), ('Administrador', 'Administrador')])),
            ],
        ),
        migrations.AddField(
            model_name='restaurante',
            name='ayudante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='catalogoapp.Usuario'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Restaurante', to='catalogoapp.Restaurante'),
        ),
    ]
