# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0002_auto_20170527_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='ayudante',
        ),
        migrations.AddField(
            model_name='perfil',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurante'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurante'),
        ),
    ]
