# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogoapp', '0003_auto_20170602_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('ingredients', models.TextField()),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('dish_choice', models.TextField(choices=[('Aperitivo', 'Aperitivo'), ('Plato Fuerte', 'Plato Fuerte'), ('Postre', 'Postre')])),
                ('temperature', models.TextField(choices=[('Frio', 'Frio'), ('Caliente', 'Caliente')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('Cliente', 'Cliente'), ('Ayudante', 'Ayudante'), ('Administrador', 'Administrador')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('adress', models.TextField()),
                ('owner', models.TextField(max_length=50)),
                ('phone_number', models.TextField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='restaurante',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Platillo',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurant'),
        ),
    ]
