# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0006_auto_20170610_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
