# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0007_auto_20170611_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='DishTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Temperaturas',
                'verbose_name': 'Temperatura',
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'verbose_name': 'Tipo',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Solo necesario si el rol es Ayudante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='catalogoapp.Restaurant'),
        ),
    ]
