# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0008_auto_20170627_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.DishType'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurant'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.DishTemperature'),
        ),
    ]
