# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0012_auto_20170812_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.PaymentMethod'),
            preserve_default=False,
        ),
    ]
