# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0013_order_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Solo necesario si el rol es Ayudante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='catalogoapp.Restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
