# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0015_auto_20170816_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.AddField(
            model_name='lunch',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Restaurant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
