# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0017_auto_20170817_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='color',
            field=models.CharField(choices=[('#ffe62b', 'Amarillo'), ('#ff982a', 'Anaranjado'), ('#ea1212', 'Rojo'), ('#ea128c', 'Fucsia'), ('#b712ea', 'Morado'), ('#1264ea', 'Azul'), ('#12ea24', 'Verde')], max_length=20),
        ),
        migrations.AlterField(
            model_name='style',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Gadget', 'Gadget'), ('Comic Sans MS', 'Comic Sans MS'), ('Impact', 'Impact'), ('Charcoal', 'Charcoal'), ('Tahoma', 'Tahoma'), ('Helvetica', 'Helvetica'), ('Trebuchet MS', 'Trebuchet MS'), ('Courier New', 'Courier New'), ('Lucida Console', 'Lucida Console'), ('Monaco', 'Monaco')], max_length=30),
        ),
        migrations.AlterField(
            model_name='style',
            name='size',
            field=models.IntegerField(choices=[(12, 12), (14, 14), (16, 16), (18, 18), (20, 20)]),
        ),
    ]
