# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0019_auto_20170818_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
