# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0020_auto_20170817_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_set', related_query_name='profiles', to='catalogoapp.Restaurant'),
        ),
    ]
