# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0021_auto_20170819_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Schedules',
                'verbose_name': 'Schedule',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Schedule'),
            preserve_default=False,
        ),
    ]
