# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0022_auto_20170819_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executivelunch',
            options={'verbose_name': 'Executive lunch', 'verbose_name_plural': 'Executive lunches'},
        ),
    ]
