# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0024_auto_20170819_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Lunch'),
        ),
    ]
