# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0025_auto_20170819_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carnetmethod',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='creditcardmethod',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogoapp.Lunch'),
        ),
    ]
