# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0026_auto_20170820_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
