# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0027_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carnetmethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creditcardmethod',
        ),
        migrations.RemoveField(
            model_name='style',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
