# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0030_auto_20170820_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
