# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0031_auto_20170821_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
